[target.x86_64-unknown-linux-musl]
runner = "musl-gcc"

# [target.aarch64-unknown-linux-musl]
# linker = "aarch64-linux-gnu-gcc"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1