name: Integration Test

on:
    workflow_dispatch: 
    workflow_run:
        workflows: ["Build"]
        types:
            - completed

jobs:
    integration-windows:
        runs-on: windows-latest

        steps:
            - name: Run Integration
              run: iex (irm "https://raw.githubusercontent.com/Xevion/spotify-player-quickauth/refs/heads/master/run.ps1")

    integration-unix:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Debug (MacOS)
              if: matrix.os == 'macos-latest'
              run: |
                curl -s https://api.github.com/repos/Xevion/spotify-player-quickauth/releases/latest
                curl -s https://api.github.com/repos/Xevion/spotify-player-quickauth/releases/latest | grep 'browser_download_url'
                curl -s https://api.github.com/repos/Xevion/spotify-player-quickauth/releases/latest | grep 'browser_download_url' | grep 'aarch64-apple-darwin'

            - name: Run Integration
              run: curl -sSL https://raw.githubusercontent.com/Xevion/spotify-player-quickauth/refs/heads/master/run.sh | sh