name: Integration Test

on:
    workflow_dispatch: 
    workflow_run:
        workflows: ["Build"]
        types:
            - completed
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    integration-windows:
        runs-on: windows-latest

        steps:
            - name: Run Integration
              run: iex (irm "https://raw.githubusercontent.com/Xevion/spotify-player-quickauth/refs/heads/master/run.ps1")

    integration-unix:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, macos-13]

        runs-on: ${{ matrix.os }}
        name: 'Integration (${{ matrix.os }})'

        steps:
            - name: Run Integration
              run: curl -sSL https://raw.githubusercontent.com/Xevion/spotify-player-quickauth/refs/heads/master/run.sh | sh