name: Integration Test

on:
    workflow_run:
        workflows: ["Build"]
        types:
            - completed

jobs:
    integration:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Run Integration
              if: ${{ !contains(matrix.os, 'windows') }}
              run: curl -sSL https://raw.githubusercontent.com/Xevion/spotify-player-quickauth/refs/heads/master/run.sh | sh
            
            - name: Run Integration (Windows)
              if: ${{ contains(matrix.os, 'windows') }}
              run: iex (irm "https://raw.githubusercontent.com/Xevion/spotify-player-quickauth/refs/heads/master/run.ps1")